apiVersion: v1
kind: Service
metadata:
  name: {{ template "distribution.fullname" . }}
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.distribution.service.annotations }}
  annotations:
{{ toYaml .Values.distribution.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.distribution.service.type }}
  ports:
  - name: distribution
    port: {{ .Values.distribution.externalPort }}
    targetPort: distribution
  selector:
    app: {{ template "distribution.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.distribution.name }}
