apiVersion: v1
kind: Secret
metadata:
  name: {{ template "distribution.fullname" . }}-mongo-connection
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mongodb.mongodbRootPassword }}
  adminPassword: {{ .Values.mongodb.mongodbRootPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.mongodbPassword }}
  distributionPassword: {{ .Values.mongodb.mongodbPassword | b64enc | quote }}
  {{- else }}
  distributionPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

