sudo: required
dist: trusty

services:
  - docker

env:
  global:
  - CHART_TESTING_TAG="v1.1.0"
  - CHARTS_REPO="https://github.com/rimusz/jfrog-charts"

before_script:
- docker pull gcr.io/kubernetes-charts-ci/chart-testing:"${CHART_TESTING_TAG}"

script:
- echo "Run charts-testing linting!"
- ./test/lint-charts.sh

notifications:
  email: false
