steps:

# Fetch GKE cluster credentials for charts testing
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=charts-testing-ci'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']

# Run charts testing
- name: 'gcr.io/kubernetes-charts-ci/chart-testing:v1.1.0'
  env:
  - 'KUBECONFIG=/workspace/.kube/config'
  - 'CHARTS_REPO=https://github.com/rimusz/jfrog-charts'
  - 'HELM_HOST=localhost:44134'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    helm init --client-only
    helm plugin install https://github.com/rimusz/helm-tiller
    helm tiller start-ci >/dev/null 2>&1
    mkdir -p /workspace/tmp
    cd /workspace/tmp
    git clone --depth=50 "$${CHARTS_REPO}"
    cd jfrog-charts
    git config --add remote.origin.fetch +refs/pull/*/head:refs/remotes/origin/pull/*
    git fetch origin
    git checkout "$(git describe --all --contains $COMMIT_SHA)"
    git remote add k8s "$${CHARTS_REPO}"
    git fetch k8s master
    chart_test.sh --config /workspace/test/.testenv
