version: 2

jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/e2e-docker4mac.sh
            shellcheck -x test/e2e-gke.sh
            shellcheck -x test/e2e-local-gke.sh
            shellcheck -x test/lint-charts.sh
  lint-charts:
    machine: true
    environment:
      CHART_TESTING_TAG: v1.1.0
      CHARTS_REPO: https://github.com/rimusz/jfrog-charts
    steps:
      - checkout
      - run:
          name: lint
          command: |
            test/lint-charts.sh
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: gcr.io/kubernetes-charts-ci/chart-testing
      CHART_TESTING_TAG: v1.1.0
      CHARTS_REPO: https://github.com/rimusz/jfrog-charts
      CHANGE_MINIKUBE_NONE_USER: true
      K8S_VERSION: v1.10.0
      MINIKUBE_VERSION: v0.28.2
    steps:
      - checkout
      - run:
          name: install
          command: |
            test/e2e-minikube.sh
          no_output_timeout: 3600
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
