version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/e2e-docker4mac.sh
            shellcheck -x test/e2e-gke.sh
            shellcheck -x test/e2e-local-gke.sh
            shellcheck -x test/lint-charts.sh
  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/chart-testing:v1.1.0
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add k8s https://github.com/rimusz/jfrog-charts
            git fetch k8s master
            chart_test.sh --config test/.testenv --no-install
workflows:
  version: 2
  lint:
    jobs:
      - lint-scripts
      - lint-charts
