version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/e2e-docker4mac.sh
            shellcheck -x test/e2e-gke.sh
            shellcheck -x test/e2e-local-gke.sh
            shellcheck -x test/lint-charts.sh
  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/chart-testing:v1.1.0
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add k8s https://github.com/rimusz/jfrog-charts
            git fetch k8s master
            chart_test.sh --config test/.testenv --no-install
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: gcr.io/kubernetes-charts-ci/chart-testing
      CHART_TESTING_TAG: v1.1.0
      TEST_IMAGE: gcr.io/kubernetes-charts-ci/test-image
      TEST_IMAGE_TAG: v2.0.5
      CHARTS_REPO: https://github.com/rimusz/jfrog-charts
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      K8S_VERSION: v1.10.0
      MINIKUBE_VERSION: v0.28.2
    steps:
      - checkout
      - run:
          name: install
          command: |
            test/e2e-circleci.sh
          no_output_timeout: 3600
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
